### ISSUE TITLE
Running in WSL issue

### ISSUE THREAD

**Issue by Zygoatgal** [Benex254/yt-x#1]
When i run the yt-x ui it starts and the only messages it sends are "invalid color specification: label: #aeaeae/invalid action"
What can I do to help resolve this issue?

**Comment by Benex254** [comment]
I am currently working on reimplementing the preview logic. Plus i dont't use WSL. So you will have to wait for quite sometime before this is ever resolved

**Comment by Benex254** [comment]
Could you give more details on this issue?

**Comment by Benex254** [comment]
This  is an fzf version issue. It should be 0.56.0
